apiVersion: v1
kind: Service
metadata:
  name: kind-broker-service
spec:
  ports:
  - nodePort: 30950
    port: 8883
    protocol: TCP
    targetPort: 8883
  selector:
    app: astarte-vernemq
  type: NodePort
